spring:
  application:
    name: muchos-a-muchos03

  datasource:
    url: jdbc:mysql://localhost:3306/quantum_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  server:
    port: 8081